### ISSUE TITLE
Need to install matplotlib

### ISSUE THREAD

**Issue by evasterviga** [jringlander/virus-drifting#1]
Hej :)

Får detta felet när jag testkör din kod:

```
Traceback (most recent call last):
  File "/home/xaemmo/python_course/student_projects/virus-drifting/viruscode.py", line 5, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
```

Nåonstans, kanske requirements, behöver du visa hur matplotlib installeras. 
Försök gärna göra README:n lite mer läsbar genom att göra tex code blocks när du visar hur man ska köra och installera saker. ( <https://www.markdownguide.org/basic-syntax/#code> )

**Comment by jringlander** [comment]
Tack för feedbacken!

Nu är README lite snyggare. Nu borde det funka?

Mvh
Johan
________________________________
Från: EmmaCAndersson ***@***.***>
Skickat: den 21 oktober 2022 16:47
Till: jringlander/virus-drifting ***@***.***>
Kopia: Subscribed ***@***.***>
Ämne: [jringlander/virus-drifting] Need to install matplotlib (Issue #1)


Hej :)

Får detta felet när jag testkör din kod:

Traceback (most recent call last):

  File "/home/xaemmo/python_course/student_projects/virus-drifting/viruscode.py", line 5, in <module>

    import matplotlib.pyplot as plt

ModuleNotFoundError: No module named 'matplotlib'



Nåonstans, kanske requirements, behöver du visa hur matplotlib installeras.
Försök gärna göra README:n lite mer läsbar genom att göra tex code blocks när du visar hur man ska köra och installera saker. ( https://www.markdownguide.org/basic-syntax/#code )
